# This is the main configuration file for your site.
[build]
  # This command is run when you deploy the site.
  command = "npm install"
  # The directory where your website's files are.
  publish = "/"
  
  # Set environment variables for the build
  [build.environment]
    # Use Node.js 18 for compatibility with dependencies
    NODE_VERSION = "18"

# Explicitly define the functions directory.
[functions]
  directory = "netlify/functions"

# Configuration for ALL Netlify Functions.
[functions."*"]
  # Use the 'zisi' bundler instead of 'esbuild'. This can resolve
  # environment linking issues.
  node_bundler = "zisi"
  
  # This line remains critical. It tells the bundler to use the native
  # version of the blobs library from the Netlify runtime.
  external_node_modules = ["@netlify/blobs"]

# Enable Netlify Blob Storage
[stores]
  # Name of the blob store we will use
  audio_uploads = "Audio Uploads"
