# This is the main configuration file for your site.
[build]
  # This command is run when you deploy the site.
  command = "npm install"
  # The directory where your website's files are.
  publish = "/"
  
  # Set environment variables for the build
  [build.environment]
    # Use Node.js 18 for compatibility with dependencies
    NODE_VERSION = "18"

# Explicitly define the functions directory. This helps ensure the
# settings below are applied correctly.
[functions]
  directory = "netlify/functions"

# Configuration for ALL Netlify Functions.
# The wildcard "*" applies these settings to every function.
[functions."*"]
  node_bundler = "esbuild"
  # CRITICAL FIX: This line tells the bundler NOT to include the
  # "@netlify/blobs" library in the function's code bundle.
  # The function will instead use the native version of the library
  # that is already available and authenticated in the Netlify runtime.
  external_node_modules = ["@netlify/blobs"]

# Enable Netlify Blob Storage
[stores]
  # Name of the blob store we will use
  audio_uploads = "Audio Uploads"
