# This is the main configuration file for your site.
[build]
  command = "npm install"
  publish = "/"
  
  [build.environment]
    NODE_VERSION = "18"

# Define the functions directory and apply settings directly.
[functions]
  directory = "netlify/functions"
  # Switch to the 'nft' (Node File Tracing) bundler.
  node_bundler = "nft"
  
  # This line remains critical. It tells the bundler to use the native
  # version of the blobs library from the Netlify runtime.
  external_node_modules = ["@netlify/blobs"]

# Enable Netlify Blob Storage
[stores]
  audio_uploads = "Audio Uploads"

