# This is the main configuration file for your site.
[build]
  # This command is run when you deploy the site.
  command = "npm install"
  # The directory where your website's files are.
  publish = "/"

# Configuration for Netlify Functions
[functions]
  directory = "netlify/functions/"
  # Use Node.js 18 for compatibility
  node_bundler = "esbuild"
  node_version = "18"

# Enable Netlify Blob Storage
[stores]
  # Name of the blob store we will use
  audio_uploads = "Audio Uploads"

# Configure the background function to run longer
[functions."process-audio-background"]
  schedule = "@asap" # This makes it a background function
