# This is the main configuration file for your site.
[build]
  # This command is run when you deploy the site.
  command = "npm install"
  # The directory where your website's files are.
  publish = "/"
  
  # Set environment variables for the build
  [build.environment]
    # Use Node.js 18 for compatibility with dependencies
    NODE_VERSION = "18"

# Configuration for Netlify Functions
[functions]
  directory = "netlify/functions/"
  node_bundler = "esbuild"

# Enable Netlify Blob Storage
[stores]
  # Name of the blob store we will use
  audio_uploads = "Audio Uploads"

# Configure the background function to run longer
[functions."process-audio-background"]
  schedule = "@asap" # This makes it a background function

